[audio]
chunk_size = 512
sample_rate = 48000
host_api = 'MME'
input_device = 'OBSMicL (Virtual Audio Cable)'
output_device = 'Speakers (Focusrite USB Audio)'
latency = 'low'
analysis_lib = 'librosa'

[files] # All relative paths here should be relative to the config file
external_libraries = ['../externals/SpeechToolkit']
model_dir = '../models'